====== WebDriver manager ======
Current google-chrome version is 99.0.4844
Get LATEST chromedriver version for 99.0.4844 google-chrome
Driver [/home/alexzuzow/.wdm/drivers/chromedriver/linux64/99.0.4844.51/chromedriver] found in cache
7.264670289502565 -199.86801786575265
(25, 36)
================
================
Score:  0
step time: 1.1144079599998804
(25, 36)
================
================
Score:  0
step time: 1.0238777240010677
(25, 36)
================
================
Score:  0
step time: 1.0234618829999818
(25, 36)
================
================
Score:  0
step time: 1.043844480000189
(25, 36)
================
================
Score:  0
step time: 1.076801945000625
(25, 36)
================
================
Score:  0
step time: 0.9788824759998533
(25, 36)
================
================
Score:  0
step time: 1.0839151100008166
(25, 36)
================
================
Score:  0
step time: 1.0395998809999583
(25, 36)
================
================
Score:  0
step time: 1.0279262050007674
(25, 36)
================
================
Score:  0
step time: 1.032094350000989
(25, 36)
================
================
Score:  0
step time: 1.0566341889989417
(25, 36)
================
================
Score:  0
step time: 1.0796381430009205
(25, 36)
================
================
Score:  0
step time: 1.09568428700004
(25, 36)
================
================
Traceback (most recent call last):
  File "/home/alexzuzow/Desktop/agar_multiagent/train_DQN.py", line 136, in <module>
    next_state,score,failed,restart,done = agar1.step(action,timestep,episode)
  File "/home/alexzuzow/Desktop/agar_multiagent/agar.py", line 151, in step
    obs_2 = self.get_screenshot("f2.png")
  File "/home/alexzuzow/Desktop/agar_multiagent/agar.py", line 105, in get_screenshot
    img = self.driver.get_screenshot_as_png()
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=99.0.4844.74)
Stacktrace:
#0 0x55f2833047d3 <unknown>
#1 0x55f28306051f <unknown>
#2 0x55f28304e954 <unknown>
#3 0x55f28304fa71 <unknown>
#4 0x55f283051132 <unknown>
#5 0x55f283049486 <unknown>
#6 0x55f283061a82 <unknown>
#7 0x55f2830c7118 <unknown>
#8 0x55f2830b45a3 <unknown>
#9 0x55f283089ddc <unknown>
#10 0x55f28308ade5 <unknown>
#11 0x55f28333549d <unknown>
#12 0x55f28334e60c <unknown>
#13 0x55f283337205 <unknown>
#14 0x55f28334eee5 <unknown>
#15 0x55f28332b070 <unknown>
#16 0x55f28336a488 <unknown>
#17 0x55f28336a60c <unknown>
#18 0x55f283383c6d <unknown>
#19 0x7f9b4e991609 <unknown>