====== WebDriver manager ======
Current google-chrome version is 99.0.4844
Get LATEST chromedriver version for 99.0.4844 google-chrome
Driver [/home/alexzuzow/.wdm/drivers/chromedriver/linux64/99.0.4844.51/chromedriver] found in cache
192.58262180459064 53.96233666984783
(25, 36)
(95, 40)
================
================
Score:  0
step time: 1.0798570449987892
(25, 36)
(95, 40)
================
================
Score:  0
step time: 1.0901378109992947
(25, 36)
(95, 40)
================
================
Score:  0
step time: 1.1372035180011153
(25, 36)
(95, 40)
================
================
Score:  0
step time: 1.213267471999643
(25, 36)
(95, 40)
================
================
Score:  0
step time: 1.1367133900002955
(25, 36)
(95, 40)
================
================
Score:  0
step time: 1.1851659510011814
(25, 36)
(95, 40)
================
================
Score:  0
step time: 1.1377118149994203
(25, 36)
(95, 40)
================
================
Score:  0
step time: 1.1266876000008779
(25, 36)
(95, 40)
Traceback (most recent call last):
  File "/home/alexzuzow/Desktop/agar_multiagent/train_DQN.py", line 136, in <module>
    next_state,score,failed,restart,done = agar1.step(action,timestep,episode)
  File "/home/alexzuzow/Desktop/agar_multiagent/agar.py", line 151, in step
    obs_2 = self.get_screenshot("f2.png")
  File "/home/alexzuzow/Desktop/agar_multiagent/agar.py", line 105, in get_screenshot
    img = self.driver.get_screenshot_as_png()
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=99.0.4844.74)
Stacktrace:
#0 0x55e4167ae7d3 <unknown>
#1 0x55e41650a688 <unknown>
#2 0x55e4164ea3ec <unknown>
#3 0x55e416561c9b <unknown>
#4 0x55e4165710c5 <unknown>
#5 0x55e41655e5a3 <unknown>
#6 0x55e416533ddc <unknown>
#7 0x55e416534de5 <unknown>
#8 0x55e4167df49d <unknown>
#9 0x55e4167f860c <unknown>
#10 0x55e4167e1205 <unknown>
#11 0x55e4167f8ee5 <unknown>
#12 0x55e4167d5070 <unknown>
#13 0x55e416814488 <unknown>
#14 0x55e41681460c <unknown>
#15 0x55e41682dc6d <unknown>
#16 0x7fc001ccb609 <unknown>
================
================
Score:  0
step time: 1.1312571559992648
(25, 36)
(95, 40)
================
================