====== WebDriver manager ======
Current google-chrome version is 99.0.4844
Get LATEST chromedriver version for 99.0.4844 google-chrome
Driver [/home/alexzuzow/.wdm/drivers/chromedriver/linux64/99.0.4844.51/chromedriver] found in cache
143.96689560086455 -138.82915029290416
2
3
1
Score:  1011
====================================================================
step time: 0.3004858869999225
/home/alexzuzow/Desktop/agar_multiagent/utils.py:175: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  outputs.append(torch.nn.functional.softmax(classifier(digits[i]).squeeze(0)))
====== WebDriver manager ======
Current google-chrome version is 99.0.4844
Get LATEST chromedriver version for 99.0.4844 google-chrome
Driver [/home/alexzuzow/.wdm/drivers/chromedriver/linux64/99.0.4844.51/chromedriver] found in cache
-21.75567125546615 198.81320571889606
2
3
1
====== WebDriver manager ======
Current google-chrome version is 99.0.4844
Get LATEST chromedriver version for 99.0.4844 google-chrome
Driver [/home/alexzuzow/.wdm/drivers/chromedriver/linux64/99.0.4844.51/chromedriver] found in cache
Score:  1011
====================================================================
step time: 0.34672591100024874
====== WebDriver manager ======
Current google-chrome version is 99.0.4844
Get LATEST chromedriver version for 99.0.4844 google-chrome
Driver [/home/alexzuzow/.wdm/drivers/chromedriver/linux64/99.0.4844.51/chromedriver] found in cache
Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=99.0.4844.74)
Stacktrace:
#0 0x55df30fbe7d3 <unknown>
#1 0x55df30d1a688 <unknown>
#2 0x55df30cfa3ec <unknown>
#3 0x55df30d71c9b <unknown>
#4 0x55df30d810c5 <unknown>
#5 0x55df30d6e5a3 <unknown>
#6 0x55df30d43ddc <unknown>
#7 0x55df30d44de5 <unknown>
#8 0x55df30fef49d <unknown>
#9 0x55df3100860c <unknown>
#10 0x55df30ff1205 <unknown>
#11 0x55df31008ee5 <unknown>
#12 0x55df30fe5070 <unknown>
#13 0x55df31024488 <unknown>
#14 0x55df3102460c <unknown>
#15 0x55df3103dc6d <unknown>
#16 0x7fb67f1fe609 <unknown>
Traceback (most recent call last):
  File "/home/alexzuzow/Desktop/agar_multiagent/agar.py", line 61, in reset
    menu = WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.XPATH,'//*[@id="nick"]')))
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 78, in until
    value = method(self._driver)
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py", line 327, in _predicate
    target = visibility_of(target)(driver)
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py", line 143, in _predicate
    return _element_if_visible(element)
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py", line 149, in _element_if_visible
    return element if element.is_displayed() == visibility else False
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 564, in is_displayed
    return self.parent.execute_script(
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 878, in execute_script
    return self.execute(command, {
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=99.0.4844.74)
Stacktrace:
#0 0x55df30fbe7d3 <unknown>
#1 0x55df30d1a688 <unknown>
#2 0x55df30cfa3ec <unknown>
#3 0x55df30d71c9b <unknown>
#4 0x55df30d810c5 <unknown>
#5 0x55df30d6e5a3 <unknown>
#6 0x55df30d43ddc <unknown>
#7 0x55df30d44de5 <unknown>
#8 0x55df30fef49d <unknown>
#9 0x55df3100860c <unknown>
#10 0x55df30ff1205 <unknown>
#11 0x55df31008ee5 <unknown>
#12 0x55df30fe5070 <unknown>
#13 0x55df31024488 <unknown>
#14 0x55df3102460c <unknown>
#15 0x55df3103dc6d <unknown>
#16 0x7fb67f1fe609 <unknown>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/alexzuzow/Desktop/agar_multiagent/train_DQN.py", line 126, in <module>
    state = agar1.reset()
  File "/home/alexzuzow/Desktop/agar_multiagent/agar.py", line 89, in reset
    self.reset()
  File "/home/alexzuzow/Desktop/agar_multiagent/agar.py", line 54, in reset
    self.driver = webdriver.Chrome(ChromeDriverManager().install(),options=self.chrome_options)
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__
    self.service.start()
  File "/home/alexzuzow/anaconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 103, in start
    sleep(0.5)
KeyboardInterrupt